name: Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_PAC_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_PAC_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          registry-url: "https://registry.npmjs.org"
      - run: yarn install --frozen-lockfile
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v3
